server:
  port: 8095
  servlet:
    context-path: /api/payments

spring:
  application:
    name: sf-paymentmanagement

  datasource:
    url: jdbc:postgresql://aws-0-ap-south-1.pooler.supabase.com:5432/postgres
    username: postgres.dupmnozhinscfkaenvev
    password: YP!sn4qU@J6!NF-
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    serialization:
      write-dates-as-timestamps: false

  cloud:
    openfeign:
      client:
        config:
          default:
            loggerLevel: full

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    root: INFO
    com.pg.payment: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    org.springframework.cloud.openfeign: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
