server:
  port: 8083
  servlet:
    context-path: /api/bookings

spring:
  application:
    name: sf-bookingmanagement

  datasource:
    url: jdbc:postgresql://ep-odd-silence-a148ir45-pooler.ap-southeast-1.aws.neon.tech:5432/neondb?sslmode=require&channel_binding=require
    username: neondb_owner
    password: npg_StK6vgYH1nJQ
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    serialization:
      write-dates-as-timestamps: false

  cloud:
    openfeign:
      client:
        config:
          default:
            loggerLevel: full

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    root: INFO
    com.cdacproject.stayfinder: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    org.springframework.cloud.openfeign: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
