spring:
  application:
    name: Auth-Service
  datasource:
    url: jdbc:postgresql://localhost:5432/stayfinderAuthService
    username: postgres
    password: root
  jpa:
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
        ddl-auto: create-drop

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka

server:
  port: 9090

jwt:
  keystore:
    location: classpath:jwt-keystore.jks
    password: password
    alias: jwt-key