spring:
  application:
    name: sf-auth

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 9091

jwt:
  keystore:
    location: classpath:jwt-keystore.jks
    password: password
    alias: jwt-key