spring:
  application:
    name: sf-property-service

  datasource:
    url: jdbc:postgresql://aws-0-ap-south-1.pooler.supabase.com:6543/postgres
    username: postgres.qwxlricixjwljrdmvecy
    password: VivekCdac@123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: your_very_long_secret_key_at_least_32_chars

gateway:
  base-url: http://api-gateway:4000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost

server:
  port: 8085
