spring:
  application:
    name: apigateway
  security:
    user:
      name: disabled
      password: disabled
  cloud:
    gateway:
      routes:
        - id: sf-auth
          uri: lb://SF-AUTH
          predicates:
            - Path=/api/auth/**
        - id: sf-usermanagement
          uri: lb://SF-USERMANAGEMENT
          predicates:
            - Path=/api/v1/user/**
        - id: sf-bookingmanagement
          uri: lb://SF-BOOKINGMANAGEMENT
          predicates:
            - Path=/api/bookings/**
        - id: sf-property-service
          uri: lb://SF-PROPERTY-SERVICE
          predicates:
            - Path=/api/pgs/**,/api/pgs/{pgId}/rooms/**
        - id: sf-payment-service
          uri: lb://SF-PAYMENT-SERVICE
          predicates:
            - Path=/api/payments/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:9091"
              - "http://localhost:8081"
              - "http://localhost:8083"
              - "http://localhost:8085"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
            allowedHeaders:
              - Content-Type
              - responseType
              - Authorization
            allowCredentials: true

  jwt:
    keystore:
      location: classpath:jwt-keystore.jks
      password: password
      alias: jwt-key

server:
  port: 8000

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: gateway