spring:
  application:
    name: SF-USERMANAGEMENT
  security:
    user:
      name: disabled
      password: disabled
  datasource:
    url: jdbc:postgresql://localhost:5432/usermanagement
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: gateway
server:
  port: 8081

